extends:
  - airbnb-base
  - prettier
env:
  node: true
  browser: true
  es6: true
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false


overrides:
  - files:
    - '*.ts'
    parser: '@typescript-eslint/parser'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    parserOptions:
      project:
        - ./tsconfig.json

settings:
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx

rules:
  prefer-const:
    - error
    - destructuring : all
  import/extensions:
    - error
    - ignorePackages
    - ts: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
